/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include <gtest/gtest.h>
#include <string>
#include <vector>

#include "py_generator.h"
#include "utils.h"
#include "graph/operator_factory.h"
#include "graph/op_desc.h"

namespace {
auto Normalize = [](const std::string &code) {
  std::string str = code;
  str.erase(std::remove_if(str.begin(), str.end(), ::isspace), str.end());
  return str;
};
}
class GenPyImplLLT : public ::testing::Test {
 protected:
  void SetUp() override {
    py_gen_ = std::make_unique<ge::es::PyGenerator>();
    py_gen_->SetModuleName("ut_test");
  }

  void TearDown() override {}

  std::unique_ptr<ge::es::PyGenerator> py_gen_;
};
// Python的参数顺序和C,C++的顺序保持一致，都是[输入，必选属性，可选属性]， 注意属性的顺序会调整，但是对python影响不大
// 因为属性是关键字参数
// 测试动态输出算子phony_1i_1dyo的Python生成
TEST_F(GenPyImplLLT, Phony1i1dyoOpPythonGeneration) {
  std::string expected_py_content = R"(#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 为 phony_1i_1dyo 定义ctypes结构体
class Cphony_1i_1dyoOutput(ctypes.Structure):
    """ctypes structure corresponding to Esphony_1i_1dyoOutput"""
    _fields_ = [
        ("dy", ctypes.POINTER(EsCTensorHolderPtr)),  # EsCTensorHolder指针数组
        ("dy_num", ctypes.c_int64),  # 动态输出数量
    ]

# 定义 phony_1i_1dyo 函数原型
esb_generated_lib.Esphony_1i_1dyo.argtypes = [EsCTensorHolderPtr, ctypes.c_int64, ctypes.POINTER(ctypes.c_int64), ctypes.c_int64]
esb_generated_lib.Esphony_1i_1dyo.restype = Cphony_1i_1dyoOutput  # Esphony_1i_1dyoOutput

# 创建Python包装函数
def phony_1i_1dyo(x: TensorHolder, dy_num: int, *, index: List[int] = [10, 10, 10]) -> List[TensorHolder]:
    """
    Python wrapper for Esphony_1i_1dyo function
    Args:
        x: TensorHolder object
        dy_num: int - number of dynamic outputs
        index: list of integers (optional)
    Returns:
        List of TensorHolder objects
    """
    # 获取owner_graph_builder
    owner_graph_builder = x.get_owner_builder()
    # 调用C函数
    _result = esb_generated_lib.Esphony_1i_1dyo(x._handle, dy_num, (ctypes.c_int64 * len(index))(*index), len(index))

    # 处理动态输出结果
    # 创建动态输出列表
    dy_list = [TensorHolder._create_from(_result.dy[i], owner_graph_builder) for i in range(_result.dy_num)]

    # 尝试获取scope内信息设置到节点上
    if dy_list:
        owner_graph_builder._apply_scope_infos_to_node(dy_list[0])

    return dy_list
)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_1i_1dyo";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

// 测试混合动态输出算子phony_1i_1dyo1o的Python生成
TEST_F(GenPyImplLLT, Phony1i1dyo1oOpPythonGeneration) {
  std::string expected_py_content = R"(#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 为 phony_1i_1dyo1o 定义ctypes结构体
class Cphony_1i_1dyo1oOutput(ctypes.Structure):
    """ctypes structure corresponding to Esphony_1i_1dyo1oOutput"""
    _fields_ = [
        ("dy", ctypes.POINTER(EsCTensorHolderPtr)),  # EsCTensorHolder指针数组
        ("dy_num", ctypes.c_int64),  # 动态输出数量
        ("y", EsCTensorHolderPtr),  # EsCTensorHolder指针
    ]

# 为 phony_1i_1dyo1o 定义输出结构体
class phony_1i_1dyo1oOutput:
    """Output structure for phony_1i_1dyo1o operator"""
    def __init__(self, dy: List[TensorHolder], y: TensorHolder):
        self.dy = dy
        self.y = y


# 定义 phony_1i_1dyo1o 函数原型
esb_generated_lib.Esphony_1i_1dyo1o.argtypes = [EsCTensorHolderPtr, ctypes.c_int64, ctypes.POINTER(ctypes.c_int64), ctypes.c_int64]
esb_generated_lib.Esphony_1i_1dyo1o.restype = Cphony_1i_1dyo1oOutput  # Esphony_1i_1dyo1oOutput

# 创建Python包装函数
def phony_1i_1dyo1o(x: TensorHolder, dy_num: int, *, index: List[int] = [10, 10, 10]) -> phony_1i_1dyo1oOutput:
    """
    Python wrapper for Esphony_1i_1dyo1o function
    Args:
        x: TensorHolder object
        dy_num: int - number of dynamic outputs
        index: list of integers (optional)
    Returns:
        phony_1i_1dyo1oOutput object containing dynamic and/or multiple outputs
    """
    # 获取owner_graph_builder
    owner_graph_builder = x.get_owner_builder()
    # 调用C函数
    _result = esb_generated_lib.Esphony_1i_1dyo1o(x._handle, dy_num, (ctypes.c_int64 * len(index))(*index), len(index))

    # 处理动态输出结果
    # 创建动态输出列表: dy
    dy_list = [TensorHolder._create_from(_result.dy[i], owner_graph_builder) for i in range(_result.dy_num)]
    y = TensorHolder._create_from(_result.y, owner_graph_builder)

    # 尝试获取scope内信息设置到节点上
    if dy_list:
        owner_graph_builder._apply_scope_infos_to_node(dy_list[0])

    return phony_1i_1dyo1oOutput(
        dy=dy_list,
        y=y,
    )
)";
  const char *op_type = "phony_1i_1dyo1o";
  // 验证python包装器内容 - 直接比较内容是否一致
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

// 测试两个动态输出算子phony_1i_2dyo的Python生成
TEST_F(GenPyImplLLT, Phony1i2dyoOpPythonGeneration) {
  std::string expected_py_content = R"(#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 为 phony_1i_2dyo 定义ctypes结构体
class Cphony_1i_2dyoOutput(ctypes.Structure):
    """ctypes structure corresponding to Esphony_1i_2dyoOutput"""
    _fields_ = [
        ("dy1", ctypes.POINTER(EsCTensorHolderPtr)),  # EsCTensorHolder指针数组
        ("dy1_num", ctypes.c_int64),  # 动态输出数量
        ("dy2", ctypes.POINTER(EsCTensorHolderPtr)),  # EsCTensorHolder指针数组
        ("dy2_num", ctypes.c_int64),  # 动态输出数量
    ]

# 为 phony_1i_2dyo 定义输出结构体
class phony_1i_2dyoOutput:
    """Output structure for phony_1i_2dyo operator"""
    def __init__(self, dy1: List[TensorHolder], dy2: List[TensorHolder]):
        self.dy1 = dy1
        self.dy2 = dy2


# 定义 phony_1i_2dyo 函数原型
esb_generated_lib.Esphony_1i_2dyo.argtypes = [EsCTensorHolderPtr, ctypes.c_int64, ctypes.c_int64, ctypes.POINTER(ctypes.c_int64), ctypes.c_int64]
esb_generated_lib.Esphony_1i_2dyo.restype = Cphony_1i_2dyoOutput  # Esphony_1i_2dyoOutput

# 创建Python包装函数
def phony_1i_2dyo(x: TensorHolder, dy1_num: int, dy2_num: int, *, index: List[int] = [10, 10, 10]) -> phony_1i_2dyoOutput:
    """
    Python wrapper for Esphony_1i_2dyo function
    Args:
        x: TensorHolder object
        dy1_num: int - number of dynamic outputs
        dy2_num: int - number of dynamic outputs
        index: list of integers (optional)
    Returns:
        phony_1i_2dyoOutput object containing dynamic and/or multiple outputs
    """
    # 获取owner_graph_builder
    owner_graph_builder = x.get_owner_builder()
    # 调用C函数
    _result = esb_generated_lib.Esphony_1i_2dyo(x._handle, dy1_num, dy2_num, (ctypes.c_int64 * len(index))(*index), len(index))

    # 处理动态输出结果
    # 创建动态输出列表: dy1
    dy1_list = [TensorHolder._create_from(_result.dy1[i], owner_graph_builder) for i in range(_result.dy1_num)]
    # 创建动态输出列表: dy2
    dy2_list = [TensorHolder._create_from(_result.dy2[i], owner_graph_builder) for i in range(_result.dy2_num)]

    # 尝试获取scope内信息设置到节点上
    if dy1_list:
        owner_graph_builder._apply_scope_infos_to_node(dy1_list[0])

    return phony_1i_2dyoOutput(
        dy1=dy1_list,
        dy2=dy2_list,
    )
)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_1i_2dyo";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}
// 测试单输入单输出算子phony_1i_1o的Python生成
TEST_F(GenPyImplLLT, Phony1i1oOpPythonGeneration) {
  std::string expected_py_content = R"(#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 定义 phony_1i_1o 函数原型
esb_generated_lib.Esphony_1i_1o.argtypes = [EsCTensorHolderPtr, ctypes.c_int64]
esb_generated_lib.Esphony_1i_1o.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_1i_1o(x: TensorHolder, *, index: int = 0) -> TensorHolder:
    """
    Python wrapper for Esphony_1i_1o function
    Args:
        x: TensorHolder object
        index: int value (optional)
    Returns:
        New TensorHolder object
    """
    # 获取owner_graph_builder
    owner_graph_builder = x.get_owner_builder()
    # 调用C函数
    _result = esb_generated_lib.Esphony_1i_1o(x._handle, index)

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder
)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_1i_1o";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

// 测试多输出算子phony_1i_2o的Python生成
TEST_F(GenPyImplLLT, Phony1i2oOpPythonGeneration) {
  std::string expected_py_content = R"(#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 为 phony_1i_2o 定义ctypes结构体
class Cphony_1i_2oOutput(ctypes.Structure):
    """ctypes structure corresponding to Esphony_1i_2oOutput"""
    _fields_ = [
        ("y1", EsCTensorHolderPtr),  # EsCTensorHolder指针
        ("y2", EsCTensorHolderPtr),  # EsCTensorHolder指针
    ]

# 为 phony_1i_2o 定义输出结构体
class phony_1i_2oOutput:
    """Output structure for phony_1i_2o operator"""
    def __init__(self, y1: TensorHolder, y2: TensorHolder):
        self.y1 = y1
        self.y2 = y2


# 定义 phony_1i_2o 函数原型
esb_generated_lib.Esphony_1i_2o.argtypes = [EsCTensorHolderPtr]
esb_generated_lib.Esphony_1i_2o.restype = Cphony_1i_2oOutput  # Esphony_1i_2oOutput

# 创建Python包装函数
def phony_1i_2o(x: TensorHolder) -> phony_1i_2oOutput:
    """
    Python wrapper for Esphony_1i_2o function
    Args:
        x: TensorHolder object
    Returns:
        phony_1i_2oOutput object containing multiple outputs
    """
    # 获取owner_graph_builder
    owner_graph_builder = x.get_owner_builder()
    # 调用C函数
    _result = esb_generated_lib.Esphony_1i_2o(x._handle)

    # 处理多输出结果
    y1 = TensorHolder._create_from(_result.y1, owner_graph_builder)
    y2 = TensorHolder._create_from(_result.y2, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(y1)
    return phony_1i_2oOutput(
        y1=y1,
        y2=y2,
    )
)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_1i_2o";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

// 测试多属性算子phony_multi_attr的Python生成
TEST_F(GenPyImplLLT, PhonyMultiAttrOpPythonGeneration) {
  std::string expected_py_content = R"(#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 定义 phony_multi_attr 函数原型
esb_generated_lib.Esphony_multi_attr.argtypes = [EsCGraphBuilderPtr, ctypes.POINTER(ctypes.c_int64), ctypes.c_int64, ctypes.c_float, ctypes.c_char_p, ctypes.c_bool, ctypes.POINTER(ctypes.c_float), ctypes.c_int64, ctypes.POINTER(ctypes.c_bool), ctypes.c_int64]
esb_generated_lib.Esphony_multi_attr.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_multi_attr(owner_graph_builder: GraphBuilder, *, li: List[int] = [10, 10, 10], f: float = 0.000000, s: str = "s", b: bool = True, lf: List[float] = [0.100000, 0.200000], lb: List[bool] = [False, True]) -> TensorHolder:
    """
    Python wrapper for Esphony_multi_attr function
    Args:
        owner_graph_builder: GraphBuilder object
        li: list of integers (optional)
        f: float value (optional)
        s: string (optional)
        b: boolean value (optional)
        lf: list of floats (optional)
        lb: list of booleans (optional)
    Returns:
        New TensorHolder object(does not produce an output, so the returned cannot be used to connect edges)
    """
    # 调用C函数
    _result = esb_generated_lib.Esphony_multi_attr(owner_graph_builder._handle, (ctypes.c_int64 * len(li))(*li), len(li), f, s.encode('utf-8'), b, (ctypes.c_float * len(lf))(*lf), len(lf), (ctypes.c_bool * len(lb))(*lb), len(lb))

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder
)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_multi_attr";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

// 测试动态输入算子phony_1i1dyi_1o的Python生成
TEST_F(GenPyImplLLT, Phony1i1dyi1oOpPythonGeneration) {
  std::string expected_py_content = R"(#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 定义 phony_1i1dyi_1o 函数原型
esb_generated_lib.Esphony_1i1dyi_1o.argtypes = [EsCTensorHolderPtr, ctypes.POINTER(EsCTensorHolderPtr), ctypes.c_int64, ctypes.POINTER(ctypes.c_int64), ctypes.c_int64]
esb_generated_lib.Esphony_1i1dyi_1o.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_1i1dyi_1o(x: Union[TensorHolder, TensorLike], dx: List[Union[TensorHolder, TensorLike]], *, index: List[int] = [10, 10, 10]) -> TensorHolder:
    """
    Python wrapper for Esphony_1i1dyi_1o function
    Args:
        x: TensorHolder or TensorLike object
        dx: TensorHolder or TensorLike object list
        index: list of integers (optional)
    Returns:
        New TensorHolder object
    Note: at least one of the following input arguments should be TensorHolder object:
          x
          dx
    """
    # 获取owner_graph_builder
    owner_graph_builder = resolve_builder(x, *(dx if dx else [None]))

    # 将TensorLike输入转换为TensorHolder
    x = convert_to_tensor_holder(x, owner_graph_builder)
    dx = [convert_to_tensor_holder(t, owner_graph_builder) for t in dx]

    # 转换动态输入
    dx_ptrs = [t._handle for t in dx]
    dx_array = (EsCTensorHolderPtr * len(dx))(*dx_ptrs)

    # 调用C函数
    _result = esb_generated_lib.Esphony_1i1dyi_1o(x._handle, dx_array, len(dx), (ctypes.c_int64 * len(index))(*index), len(index))

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder
)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_1i1dyi_1o";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

// 测试可选输入算子phony_1opi1i_1o的Python生成
TEST_F(GenPyImplLLT, Phony1opi1i1oOpPythonGeneration) {
  std::string expected_py_content = R"(#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 定义 phony_1opi1i_1o 函数原型
esb_generated_lib.Esphony_1opi1i_1o.argtypes = [EsCTensorHolderPtr, EsCTensorHolderPtr, ctypes.c_bool, ctypes.c_int]
esb_generated_lib.Esphony_1opi1i_1o.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_1opi1i_1o(x: Union[TensorHolder, TensorLike], dx: Optional[Union[TensorHolder, TensorLike]] = None, *, flag: bool, dt: DataType = DataType.DT_FLOAT) -> TensorHolder:
    """
    Python wrapper for Esphony_1opi1i_1o function
    Args:
        x: TensorHolder or TensorLike object
        dx: TensorHolder or TensorLike object (optional)
        flag: boolean value
        dt: DataType enum (optional)
    Returns:
        New TensorHolder object
    Note: at least one of the following input arguments should be TensorHolder object:
          x
          dx
    """
    # 获取owner_graph_builder
    owner_graph_builder = resolve_builder(x, dx)

    # 将TensorLike输入转换为TensorHolder
    x = convert_to_tensor_holder(x, owner_graph_builder)
    dx = convert_to_tensor_holder(dx, owner_graph_builder)

    # 调用C函数
    _result = esb_generated_lib.Esphony_1opi1i_1o(x._handle, (dx._handle if dx is not None else None), flag, ctypes.c_int(dt.value))

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder
)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_1opi1i_1o";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

// 测试单输入单输出单动态输出算子phony_1i_1o1dyo的Python生成
TEST_F(GenPyImplLLT, Phony1i1o1dyoOpPythonGeneration) {
  std::string expected_py_content = R"(
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 为 phony_1i_1o1dyo 定义ctypes结构体
class Cphony_1i_1o1dyoOutput(ctypes.Structure):
    """ctypes structure corresponding to Esphony_1i_1o1dyoOutput"""
    _fields_ = [
        ("y", EsCTensorHolderPtr),  # EsCTensorHolder指针
        ("dy", ctypes.POINTER(EsCTensorHolderPtr)),  # EsCTensorHolder指针数组
        ("dy_num", ctypes.c_int64),  # 动态输出数量
    ]

# 为 phony_1i_1o1dyo 定义输出结构体
class phony_1i_1o1dyoOutput:
    """Output structure for phony_1i_1o1dyo operator"""
    def __init__(self, y: TensorHolder, dy: List[TensorHolder]):
        self.y = y
        self.dy = dy


# 定义 phony_1i_1o1dyo 函数原型
esb_generated_lib.Esphony_1i_1o1dyo.argtypes = [EsCTensorHolderPtr, ctypes.c_int64]
esb_generated_lib.Esphony_1i_1o1dyo.restype = Cphony_1i_1o1dyoOutput  # Esphony_1i_1o1dyoOutput

# 创建Python包装函数
def phony_1i_1o1dyo(x: TensorHolder, dy_num: int) -> phony_1i_1o1dyoOutput:
    """
    Python wrapper for Esphony_1i_1o1dyo function
    Args:
        x: TensorHolder object
        dy_num: int - number of dynamic outputs
    Returns:
        phony_1i_1o1dyoOutput object containing dynamic and/or multiple outputs
    """
    # 获取owner_graph_builder
    owner_graph_builder = x.get_owner_builder()
    # 调用C函数
    _result = esb_generated_lib.Esphony_1i_1o1dyo(x._handle, dy_num)

    # 处理动态输出结果
    y = TensorHolder._create_from(_result.y, owner_graph_builder)
    # 创建动态输出列表: dy
    dy_list = [TensorHolder._create_from(_result.dy[i], owner_graph_builder) for i in range(_result.dy_num)]

    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(y)

    return phony_1i_1o1dyoOutput(
        y=y,
        dy=dy_list,
    )

)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_1i_1o1dyo";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

// 测试混合子图算子phony_mix_subgraphs的Python生成
TEST_F(GenPyImplLLT, PhonyMixSubgraphsOpPythonGeneration) {
  // 手动设置子图信息
  auto op = ge::OperatorFactory::CreateOperator("op_test", "phony_mix_subgraphs");
  auto op_desc = ge::OpDescUtils::GetOpDescFromOperator(op);

  std::string expected_py_content = R"(
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 为 phony_mix_subgraphs 定义ctypes结构体
class Cphony_mix_subgraphsOutput(ctypes.Structure):
    """ctypes structure corresponding to Esphony_mix_subgraphsOutput"""
    _fields_ = [
        ("output", ctypes.POINTER(EsCTensorHolderPtr)),  # EsCTensorHolder指针数组
        ("output_num", ctypes.c_int64),  # 动态输出数量
    ]


# 定义 phony_mix_subgraphs 函数原型
esb_generated_lib.Esphony_mix_subgraphs.argtypes = [EsCTensorHolderPtr, ctypes.POINTER(EsCTensorHolderPtr), ctypes.c_int64, ctypes.c_int64, ctypes.POINTER(EsCGraph), ctypes.POINTER(ctypes.POINTER(EsCGraph)), ctypes.c_int64]
esb_generated_lib.Esphony_mix_subgraphs.restype = Cphony_mix_subgraphsOutput  # Esphony_mix_subgraphsOutput

# 创建Python包装函数
def phony_mix_subgraphs(opt_input: Union[TensorHolder, TensorLike], input: List[Union[TensorHolder, TensorLike]], output_num: int, cond: Graph, branches: List[Graph]) -> List[TensorHolder]:
    """
    Python wrapper for Esphony_mix_subgraphs function
    Args:
        opt_input: TensorHolder or TensorLike object (optional)
        input: TensorHolder or TensorLike object list
        output_num: int - number of dynamic outputs
        cond: Graph object
        branches: List[Graph] - list of subgraphs
    Returns:
        List of TensorHolder objects
    Note: at least one of the following input arguments should be TensorHolder object:
          opt_input
          input
    """
    # 获取owner_graph_builder
    owner_graph_builder = resolve_builder(opt_input, *(input if input else [None]))

    # 将TensorLike输入转换为TensorHolder
    opt_input = convert_to_tensor_holder(opt_input, owner_graph_builder)
    input = [convert_to_tensor_holder(t, owner_graph_builder) for t in input]

    # 转换动态输入
    input_ptrs = [t._handle for t in input]
    input_array = (EsCTensorHolderPtr * len(input))(*input_ptrs)

    # 转移静态子图所有权到C++侧，并保持对owner的引用
    cond._transfer_ownership_when_pass_as_subgraph(owner_graph_builder)

    # 转移动态子图所有权到C++侧，并保持对owner的引用
    for _subgraph in branches:
        _subgraph._transfer_ownership_when_pass_as_subgraph(owner_graph_builder)

    # 转换动态子图句柄
    branches_handles = [ctypes.cast(g._handle, ctypes.POINTER(EsCGraph)) for g in branches]
    branches_array = (ctypes.POINTER(EsCGraph) * len(branches))(*branches_handles)

    # 调用C函数
    _result = esb_generated_lib.Esphony_mix_subgraphs((opt_input._handle if opt_input is not None else None), input_array, len(input), output_num, ctypes.cast(cond._handle,ctypes.POINTER(EsCGraph)), branches_array, len(branches))

    # 处理动态输出结果
    # 创建动态输出列表
    output_list = [TensorHolder._create_from(_result.output[i], owner_graph_builder) for i in range(_result.output_num)]
    # 尝试获取scope内信息设置到节点上
    if output_list:
        owner_graph_builder._apply_scope_infos_to_node(output_list[0])

    return output_list

)";

  // 验证python包装器内容 - 直接比较内容是否一致
  py_gen_->GenOp(op_desc);
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at("phony_mix_subgraphs");
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

TEST_F(GenPyImplLLT, Phony3opi_1oOpPythonGeneration) {
  std::string expected_py_content = R"(
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
    esb_generated_lib = get_generated_lib("libes_ut_test.so")
except RuntimeError:
    esb_generated_lib = get_generated_lib("libut_test.so")

# 定义 phony_3opi_1o 函数原型
esb_generated_lib.Esphony_3opi_1o.argtypes = [EsCTensorHolderPtr, EsCTensorHolderPtr, EsCTensorHolderPtr, EsCGraphBuilderPtr]
esb_generated_lib.Esphony_3opi_1o.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_3opi_1o(x1: Optional[Union[TensorHolder, TensorLike]] = None, x2: Optional[Union[TensorHolder, TensorLike]] = None, x3: Optional[Union[TensorHolder, TensorLike]] = None, owner_builder: Optional[GraphBuilder] = None) -> TensorHolder:
    """
    Python wrapper for Esphony_3opi_1o function
    Args:
        x1: TensorHolder or TensorLike object (optional)
        x2: TensorHolder or TensorLike object (optional)
        x3: TensorHolder or TensorLike object (optional)
        owner_builder: GraphBuilder (optional)
    Returns:
        New TensorHolder object
    Note: at least one of the following input arguments should be TensorHolder object or owner_builder should be provided:
          x1
          x2
          x3
    """
    # 获取owner_graph_builder
    owner_graph_builder = resolve_builder(x1, x2, x3, owner_builder)

    # 将TensorLike输入转换为TensorHolder
    x1 = convert_to_tensor_holder(x1, owner_graph_builder)
    x2 = convert_to_tensor_holder(x2, owner_graph_builder)
    x3 = convert_to_tensor_holder(x3, owner_graph_builder)

    # 调用C函数
    _result = esb_generated_lib.Esphony_3opi_1o((x1._handle if x1 is not None else None), (x2._handle if x2 is not None else None), (x3._handle if x3 is not None else None), owner_builder._handle if owner_builder else None)

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder

)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_3opi_1o";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

TEST_F(GenPyImplLLT, Phony1opi_1oOpPythonGeneration) {
  std::string expected_py_content = R"(
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
    esb_generated_lib = get_generated_lib("libes_ut_test.so")
except RuntimeError:
    esb_generated_lib = get_generated_lib("libut_test.so")

# 定义 phony_1opi_1o 函数原型
esb_generated_lib.Esphony_1opi_1o.argtypes = [EsCTensorHolderPtr, EsCGraphBuilderPtr, ctypes.c_bool]
esb_generated_lib.Esphony_1opi_1o.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_1opi_1o(x1: Optional[Union[TensorHolder, TensorLike]] = None, owner_builder: Optional[GraphBuilder] = None, *, flag: bool) -> TensorHolder:
    """
    Python wrapper for Esphony_1opi_1o function
    Args:
        x1: TensorHolder or TensorLike object (optional)
        owner_builder: GraphBuilder (optional)
        flag: boolean value
    Returns:
        New TensorHolder object
    Note: at least one of the following input arguments should be TensorHolder object or owner_builder should be provided:
          x1
    """
    # 获取owner_graph_builder
    owner_graph_builder = resolve_builder(x1, owner_builder)

    # 将TensorLike输入转换为TensorHolder
    x1 = convert_to_tensor_holder(x1, owner_graph_builder)

    # 调用C函数
    _result = esb_generated_lib.Esphony_1opi_1o((x1._handle if x1 is not None else None), owner_builder._handle if owner_builder else None, flag)

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder

)";

  // 验证python包装器内容 - 直接比较内容是否一致
  const char *op_type = "phony_1opi_1o";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

TEST_F(GenPyImplLLT, Phony2opi1i_1oOpPythonGeneration) {
  std::string expected_py_content = R"(
  #!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
  esb_generated_lib=get_generated_lib("libes_ut_test.so")
exceptRuntimeError:
  esb_generated_lib=get_generated_lib("libut_test.so")


# 定义 phony_2opi1i_1o 函数原型
esb_generated_lib.Esphony_2opi1i_1o.argtypes = [EsCTensorHolderPtr, EsCTensorHolderPtr, EsCTensorHolderPtr]
esb_generated_lib.Esphony_2opi1i_1o.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_2opi1i_1o(x1: Union[TensorHolder, TensorLike], x2: Union[TensorHolder, TensorLike], x3: Union[TensorHolder, TensorLike]) -> TensorHolder:
    """
    Python wrapper for Esphony_2opi1i_1o function
    Args:
        x1: TensorHolder or TensorLike object (optional)
        x2: TensorHolder or TensorLike object (optional)
        x3: TensorHolder or TensorLike object
    Returns:
        New TensorHolder object
    Note: at least one of the following input arguments should be TensorHolder object:
          x1
          x2
          x3
    """
    # 获取owner_graph_builder
    owner_graph_builder = resolve_builder(x1, x2, x3)

    # 将TensorLike输入转换为TensorHolder
    x1 = convert_to_tensor_holder(x1, owner_graph_builder)
    x2 = convert_to_tensor_holder(x2, owner_graph_builder)
    x3 = convert_to_tensor_holder(x3, owner_graph_builder)

    # 调用C函数
    _result = esb_generated_lib.Esphony_2opi1i_1o((x1._handle if x1 is not None else None), (x2._handle if x2 is not None else None), x3._handle)

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder

)";
  const char *op_type = "phony_2opi1i_1o";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}


TEST_F(GenPyImplLLT, Phony_opt_attrsOpPythonGeneration) {
  std::string expected_py_content = R"(
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
    esb_generated_lib = get_generated_lib("libes_ut_test.so")
except RuntimeError:
    esb_generated_lib = get_generated_lib("libut_test.so")

# 定义 phony_opt_attrs 函数原型
esb_generated_lib.Esphony_opt_attrs.argtypes = [EsCTensorHolderPtr, ctypes.c_int, ctypes.POINTER(ctypes.c_int), ctypes.c_int64, ctypes.POINTER(ctypes.POINTER(ctypes.c_int64)), ctypes.c_int64, ctypes.POINTER(ctypes.c_int64), EsCTensorPtr, ctypes.POINTER(ctypes.c_char_p), ctypes.c_int64]
esb_generated_lib.Esphony_opt_attrs.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_opt_attrs(x: TensorHolder, *, opt_data_type: DataType = DataType.DT_INT64, opt_list_data_type: List[DataType] = [DataType.DT_FLOAT, DataType.DT_DOUBLE], opt_list_list_int: List[List[int]] = [[1, 2, 3], [3, 2, 1]], opt_tensor: Tensor = Tensor(), opt_list_string: List[str] = ["test", "test"]) -> TensorHolder:
    """
    Python wrapper for Esphony_opt_attrs function
    Args:
        x: TensorHolder object
        opt_data_type: DataType enum (optional)
        opt_list_data_type: list of DataType (optional)
        opt_list_list_int: list of list of integers (optional)
        opt_tensor: Tensor value (optional)
        opt_list_string: list of strings (optional)
    Returns:
        New TensorHolder object
    """
    # 获取owner_graph_builder
    owner_graph_builder = x.get_owner_builder()
    # 转移Tensor所有权到C++侧，并保持对owner的引用
    opt_tensor._transfer_ownership_when_pass_as_attr(owner_graph_builder)

    # 转换字符串列表属性
    _bytes_opt_list_string = [s.encode('utf-8') if isinstance(s, str) else s for s in opt_list_string]
    _c_opt_list_string = (ctypes.c_char_p * len(_bytes_opt_list_string))(*_bytes_opt_list_string)

    # 转换二维列表属性
    _row_arrays_opt_list_list_int = [(ctypes.c_int64 * len(inner_list))(*[int(v) for v in inner_list]) for inner_list in opt_list_list_int]
    _pp_opt_list_list_int = (ctypes.POINTER(ctypes.c_int64) * len(opt_list_list_int))(*[ctypes.cast(arr, ctypes.POINTER(ctypes.c_int64)) for arr in _row_arrays_opt_list_list_int])
    _inner_num_opt_list_list_int = (ctypes.c_int64 * len(opt_list_list_int))(*[len(inner_list) for inner_list in opt_list_list_int])

    # 调用C函数
    _result = esb_generated_lib.Esphony_opt_attrs(x._handle, ctypes.c_int(opt_data_type.value), (ctypes.c_int * len(opt_list_data_type))(*[dt.value for dt in opt_list_data_type]), len(opt_list_data_type), _pp_opt_list_list_int, len(opt_list_list_int), _inner_num_opt_list_list_int, opt_tensor._handle, _c_opt_list_string, len(opt_list_string))

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder

)";
  const char *op_type = "phony_opt_attrs";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}

TEST_F(GenPyImplLLT, Phony_req_attrsOpPythonGeneration) {
  std::string expected_py_content = R"(
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------

# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ===================================================================================================================
""" This file is GENERATED by bin/gen_esb, do not edit it manually"""
import ctypes
import os
from typing import List, Optional, Union
try:
    from ge.es import GraphBuilder, TensorHolder
    from ge.es.tensor_like import TensorLike, convert_to_tensor_holder, resolve_builder
    from ge.graph.types import DataType, Format
    from ge.graph.graph import Graph
    from ge.graph.tensor import Tensor
    from ge._capi.pyes_graph_builder_wrapper import (
        get_generated_lib,
        EsCTensorHolderPtr,
        EsCGraphBuilderPtr,
        EsCTensorPtr,
        EsCGraph
    )
except ImportError as e:
    raise ImportError(f"Unable to import ge module: {e}")

# 获取生成产物C实现的so句柄
try:
    esb_generated_lib = get_generated_lib("libes_ut_test.so")
except RuntimeError:
    esb_generated_lib = get_generated_lib("libut_test.so")

# 定义 phony_req_attrs 函数原型
esb_generated_lib.Esphony_req_attrs.argtypes = [EsCTensorHolderPtr, ctypes.c_int, ctypes.POINTER(ctypes.c_int), ctypes.c_int64, ctypes.POINTER(ctypes.POINTER(ctypes.c_int64)), ctypes.c_int64, ctypes.POINTER(ctypes.c_int64), EsCTensorPtr, ctypes.POINTER(ctypes.c_char_p), ctypes.c_int64]
esb_generated_lib.Esphony_req_attrs.restype = EsCTensorHolderPtr  # EsCTensorHolder指针

# 创建Python包装函数
def phony_req_attrs(x: TensorHolder, *, req_data_type: DataType, req_list_data_type: List[DataType], req_list_list_int: List[List[int]], req_tensor: Tensor, req_list_string: List[str]) -> TensorHolder:
    """
    Python wrapper for Esphony_req_attrs function
    Args:
        x: TensorHolder object
        req_data_type: DataType enum
        req_list_data_type: list of DataType
        req_list_list_int: list of list of integers
        req_tensor: Tensor value
        req_list_string: list of strings
    Returns:
        New TensorHolder object
    """
    # 获取owner_graph_builder
    owner_graph_builder = x.get_owner_builder()
    # 转移Tensor所有权到C++侧，并保持对owner的引用
    req_tensor._transfer_ownership_when_pass_as_attr(owner_graph_builder)

    # 转换字符串列表属性
    _bytes_req_list_string = [s.encode('utf-8') if isinstance(s, str) else s for s in req_list_string]
    _c_req_list_string = (ctypes.c_char_p * len(_bytes_req_list_string))(*_bytes_req_list_string)

    # 转换二维列表属性
    _row_arrays_req_list_list_int = [(ctypes.c_int64 * len(inner_list))(*[int(v) for v in inner_list]) for inner_list in req_list_list_int]
    _pp_req_list_list_int = (ctypes.POINTER(ctypes.c_int64) * len(req_list_list_int))(*[ctypes.cast(arr, ctypes.POINTER(ctypes.c_int64)) for arr in _row_arrays_req_list_list_int])
    _inner_num_req_list_list_int = (ctypes.c_int64 * len(req_list_list_int))(*[len(inner_list) for inner_list in req_list_list_int])

    # 调用C函数
    _result = esb_generated_lib.Esphony_req_attrs(x._handle, ctypes.c_int(req_data_type.value), (ctypes.c_int * len(req_list_data_type))(*[dt.value for dt in req_list_data_type]), len(req_list_data_type), _pp_req_list_list_int, len(req_list_list_int), _inner_num_req_list_list_int, req_tensor._handle, _c_req_list_string, len(req_list_string))

    # 创建新的Python包装对象
    _tensor_holder = TensorHolder._create_from(_result, owner_graph_builder)
    # 尝试获取scope内信息设置到节点上
    owner_graph_builder._apply_scope_infos_to_node(_tensor_holder)
    return _tensor_holder

)";
  const char *op_type = "phony_req_attrs";
  py_gen_->GenOp(ge::OpDescUtils::GetOpDescFromOperator(ge::OperatorFactory::CreateOperator("op_test", op_type)));
  const std::stringstream &py_content = py_gen_->GetPerOpContents().at(op_type);
  EXPECT_EQ(Normalize(py_content.str()), Normalize(expected_py_content))
      << "Generated python wrapper content does not match expected content";
}