/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of 
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "graph_optimizer/op_compiler/op_compiler_optune.h"
#include "graph_optimizer/op_compiler/op_format_tune.h"
#include "ops_store/ops_kernel_manager.h"
#include "graph/compute_graph.h"

namespace fe {
OpCompilerOpTune::OpCompilerOpTune(const std::string& compiler_name, const std::string& engine_name,
                                   const LxFusionOptimizerPtr &lx_fusion_optimizer,
                                   const FEOpsKernelInfoStorePtr &ops_kernel_info_store_ptr)
    : OpCompiler(compiler_name, engine_name, false, lx_fusion_optimizer),
      ops_kernel_info_store_ptr_(ops_kernel_info_store_ptr) {}

OpCompilerOpTune::~OpCompilerOpTune() {}

Status OpCompilerOpTune::RunCompileProcess(ge::ComputeGraph& graph) {
  /* Some nodes needs to be re-pre-compiled after Ub fusion matching.
   * Because there format or data type. */
  FE_LOGD("Running compile process graph %s for OpTune.", graph.GetName().c_str());
  Status ret;
  OpCompilerFormatTunePtr op_compiler_format_tune_ptr = nullptr;
  FE_MAKE_SHARED(op_compiler_format_tune_ptr = std::make_shared<OpCompilerFormatTune>(engine_name_),
                 return fe::OP_COMPILER_MAKE_SHARED_FAILED);
  FE_CHECK_NOTNULL(op_compiler_format_tune_ptr);
  op_compiler_format_tune_ptr->SetTuneFormatReq(graph, ops_kernel_info_store_ptr_);
  bool need_re_precompile_graph = false;
  (void)ge::AttrUtils::GetBool(graph, NEED_RE_PRECOMPILE, need_re_precompile_graph);
  if (need_re_precompile_graph) {
    ret = PreCompileOp(graph);
    if (ret != SUCCESS) {
      REPORT_FE_ERROR("[SubGraphOpt][Compile][Optune] PreCompileOp failed after buffer fusion for graph [%s].",
                      graph.GetName().c_str());
      return ret;
    }
  }

  std::vector<ge::NodePtr> buff_fus_compile_failed_nodes;
  CompileInfoParam compile_info(buff_fus_compile_failed_nodes);
  vector<ge::NodePtr> nodes_be_compiled;
  vector<ge::NodePtr> buff_fus_rollback_nodes;

  ret = OpCompiler::GetFusionScope(graph, buff_fus_rollback_nodes, compile_info.fusion_nodes_map, nodes_be_compiled);
  if (ret != SUCCESS) {
    return ret;
  }

  /* This compile is for getting a graph which will be successfully compiled(for those failed fusion-nodes, we
   * will roll it back to single node). In ms-tune process, graph also goes through this process. So for
   * matching the lx-fusion strategy in op-tune, we need to compile and roll-back first. */
  compile_info.compile_strategy = CompileStrategy::COMPILE_STRATEGY_KEEP_OPTUNE;
  ret = CompileOpOnly(compile_info);
  if (ret != SUCCESS) {
    return ret;
  }

  LxFusionOptimizeResult buffer_ret = LxFusionOptimizeResult::NO_FUSION_STRATEGY;
  FE_CHECK_NOTNULL(lx_fusion_optimizer_ptr_);
  bool need_re_compile = false;
  /* Call lx-fusion to optimize the graph. */
  ret = lx_fusion_optimizer_ptr_->LxFusionOptimize(graph, buffer_ret, need_re_compile);
  if (ret != SUCCESS && ret != tune::NO_FUSION_STRATEGY) {
    REPORT_FE_ERROR("[SubGraphOpt][Compile][Optune] BufferFusionProcess failed for graph %s result %u.",
                    graph.GetName().c_str(), ret);
    return FAILED;
  }

  if (GenerateFormatTuneResult(graph, buffer_ret, need_re_compile) != SUCCESS) {
    REPORT_FE_ERROR("[SubGraphOpt][FormatTune] Failed to update tuneFormat by cannkb result for graph %s.",
                    graph.GetName().c_str());
    return FAILED;
  }

  // In op tuning mode, precompile only needs to be done with all new
  // nodes which are generated by lx-fusion.
  // And the compile is necessary for those which are set attribute
  // "compile_strategy". For now, because the compilation time cost is not
  // that important, we just compile all nodes. And module Te-fusion will differentiate
  // compile_strategy.
  if (buffer_ret != LxFusionOptimizeResult::NO_FUSION_STRATEGY) {
    ret = PreCompileOp(graph);
    if (ret != SUCCESS) {
      REPORT_FE_ERROR("[SubGraphOpt][Compile][Optune] Re-precompile failed after LX fusion for graph [%s].",
                      graph.GetName().c_str());
      return ret;
    }
  }

  compile_info.fusion_nodes_map.clear();
  compile_info.compile_ret_map.clear();
  compile_info.buff_fus_to_del_nodes.clear();
  compile_info.compile_strategy = CompileStrategy::COMPILE_STRATEGY_OP_SPEC;
  nodes_be_compiled.clear();

  ret = OpCompiler::GetFusionScope(graph, buff_fus_rollback_nodes,
                                   compile_info.fusion_nodes_map, nodes_be_compiled);
  if (ret != SUCCESS) {
    return FAILED;
  }
  /* Here we try to re-compile every op to do the op-tune.
   * This step is to generate json for every nodes. */
  ret = CompileOpOnly(compile_info);
  if (ret != SUCCESS) {
    return ret;
  }

  return SUCCESS;
}

Status OpCompilerOpTune::UpdateNodeCompileParams(const ge::NodePtr &node,
                                                 const OpKernelInfoPtr &op_kernel_info_ptr) const {
  ge::OpDescPtr op_desc_ptr = node->GetOpDesc();
  FE_CHECK_NOTNULL(op_desc_ptr);
  FE_LOGD("[OpTuneCompile] Set compile parameters for node[%s, %s].",
          op_desc_ptr->GetName().c_str(), op_desc_ptr->GetType().c_str());
  bool is_dynamic_impl = false;
  (void)ge::AttrUtils::GetBool(op_desc_ptr, ATTR_NAME_IS_OP_DYNAMIC_IMPL, is_dynamic_impl);
  if (op_kernel_info_ptr->GetDynamicCompileStatic() == DynamicCompileStatic::TUNE) {
    (void)ge::AttrUtils::SetBool(op_desc_ptr, kAttrDynamicCompileStatic, is_dynamic_impl);
    FE_LOGD("Attribute [%s][%d] has been assigned to the node.", kAttrDynamicCompileStatic.c_str(), is_dynamic_impl);
  }
  const std::string &op_impl_switch = op_kernel_info_ptr->GetOpImplSwitch();
  if (!op_impl_switch.empty()) {
    (void)ge::AttrUtils::SetStr(op_desc_ptr, kAttrOpImplSwitch, op_impl_switch);
    FE_LOGD("Attribute [%s][%s] has been assigned to the node.", kAttrOpImplSwitch.c_str(), op_impl_switch.c_str());
  }
  return SUCCESS;
}
}
