/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of 
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "graph/utils/node_utils.h"
#include "graph/utils/graph_utils.h"
#include "graph_builder/bg_identity.h"
#include "graph_builder/converter_checker.h"
#include "register/node_converter_registry.h"
#include "common/debug/ge_log.h"

namespace gert {
namespace {
std::string FormatUnsupportedV1ControlOpsMsg(const ge::NodePtr &node) {
  std::stringstream ss;
  ss << "Node " << node->GetName().c_str() << "(" << node->GetType().c_str()
     << ") is a lower op generated by tensorflow V1 control ops and is no longer supported, "
        "you should replace it with V2 version: "
     << std::endl
     << "add following codes at the beginning of your script:" << std::endl
     << "    tf.enable_control_flow_v2()" << std::endl
     << "    tf.enable_resource_variables()" << std::endl
     << "NB: If the problem persists after configuration, you need to additionally add: " << std::endl
     << "    config.graph_options.rewrite_options.function_optimization = RewriterConfig.OFF" << std::endl
     << " in the tensorflow Session config to explicitly disable function optimization.";
  return ss.str();
}
}  // namespace

LowerResult LoweringTransparentTransmissionInput(const ge::NodePtr &node, const LowerInput &lower_input) {
  GELOGE(ge::FAILED, "%s", FormatUnsupportedV1ControlOpsMsg(node).c_str());
  LowerResult ret;
  ret.out_addrs.insert(ret.out_addrs.cbegin(), lower_input.input_addrs.cbegin(), lower_input.input_addrs.cend());
  ret.out_shapes.insert(ret.out_shapes.cbegin(), lower_input.input_shapes.cbegin(), lower_input.input_shapes.cend());
  return ret;
}

LowerResult LoweringUnsupportedV1ControlOps(const ge::NodePtr &node, const LowerInput &lower_input) {
  (void)lower_input;
  LOWER_REQUIRE(false, "%s", FormatUnsupportedV1ControlOpsMsg(node).c_str());
}

REGISTER_NODE_CONVERTER("StreamActive", LoweringTransparentTransmissionInput);
REGISTER_NODE_CONVERTER("StreamSwitch", LoweringUnsupportedV1ControlOps);
REGISTER_NODE_CONVERTER("StreamMerge", LoweringUnsupportedV1ControlOps);

REGISTER_NODE_CONVERTER("Enter", LoweringUnsupportedV1ControlOps);
REGISTER_NODE_CONVERTER("RefEnter", LoweringUnsupportedV1ControlOps);
REGISTER_NODE_CONVERTER("NextIteration", LoweringUnsupportedV1ControlOps);
REGISTER_NODE_CONVERTER("RefNextIteration", LoweringUnsupportedV1ControlOps);
}  // namespace gert
