# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph_library.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import graph_pb2 as graph__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph_library.proto',
  package='domi.tensorflow',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13graph_library.proto\x12\x0f\x64omi.tensorflow\x1a\x0bgraph.proto\"D\n\nGeGraphDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x05graph\x18\x02 \x01(\x0b\x32\x19.domi.tensorflow.GraphDef\"A\n\x0fGraphDefLibrary\x12.\n\tgraph_def\x18\x01 \x03(\x0b\x32\x1b.domi.tensorflow.GeGraphDefb\x06proto3'
  ,
  dependencies=[graph__pb2.DESCRIPTOR,])




_GEGRAPHDEF = _descriptor.Descriptor(
  name='GeGraphDef',
  full_name='domi.tensorflow.GeGraphDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='domi.tensorflow.GeGraphDef.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='graph', full_name='domi.tensorflow.GeGraphDef.graph', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=121,
)


_GRAPHDEFLIBRARY = _descriptor.Descriptor(
  name='GraphDefLibrary',
  full_name='domi.tensorflow.GraphDefLibrary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph_def', full_name='domi.tensorflow.GraphDefLibrary.graph_def', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=188,
)

_GEGRAPHDEF.fields_by_name['graph'].message_type = graph__pb2._GRAPHDEF
_GRAPHDEFLIBRARY.fields_by_name['graph_def'].message_type = _GEGRAPHDEF
DESCRIPTOR.message_types_by_name['GeGraphDef'] = _GEGRAPHDEF
DESCRIPTOR.message_types_by_name['GraphDefLibrary'] = _GRAPHDEFLIBRARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeGraphDef = _reflection.GeneratedProtocolMessageType('GeGraphDef', (_message.Message,), {
  'DESCRIPTOR' : _GEGRAPHDEF,
  '__module__' : 'graph_library_pb2'
  # @@protoc_insertion_point(class_scope:domi.tensorflow.GeGraphDef)
  })
_sym_db.RegisterMessage(GeGraphDef)

GraphDefLibrary = _reflection.GeneratedProtocolMessageType('GraphDefLibrary', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHDEFLIBRARY,
  '__module__' : 'graph_library_pb2'
  # @@protoc_insertion_point(class_scope:domi.tensorflow.GraphDefLibrary)
  })
_sym_db.RegisterMessage(GraphDefLibrary)


# @@protoc_insertion_point(module_scope)
