# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import node_def_pb2 as node__def__pb2
import function_pb2 as function__pb2
import versions_pb2 as versions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph.proto',
  package='domi.tensorflow',
  syntax='proto3',
  serialized_options=b'\n\030org.tensorflow.frameworkB\013GraphProtosP\001\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgraph.proto\x12\x0f\x64omi.tensorflow\x1a\x0enode_def.proto\x1a\x0e\x66unction.proto\x1a\x0eversions.proto\"\xa8\x01\n\x08GraphDef\x12&\n\x04node\x18\x01 \x03(\x0b\x32\x18.domi.tensorflow.NodeDef\x12-\n\x08versions\x18\x04 \x01(\x0b\x32\x1b.domi.tensorflow.VersionDef\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x34\n\x07library\x18\x02 \x01(\x0b\x32#.domi.tensorflow.FunctionDefLibraryB,\n\x18org.tensorflow.frameworkB\x0bGraphProtosP\x01\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[node__def__pb2.DESCRIPTOR,function__pb2.DESCRIPTOR,versions__pb2.DESCRIPTOR,])




_GRAPHDEF = _descriptor.Descriptor(
  name='GraphDef',
  full_name='domi.tensorflow.GraphDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='domi.tensorflow.GraphDef.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='versions', full_name='domi.tensorflow.GraphDef.versions', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='domi.tensorflow.GraphDef.version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='library', full_name='domi.tensorflow.GraphDef.library', index=3,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=249,
)

_GRAPHDEF.fields_by_name['node'].message_type = node__def__pb2._NODEDEF
_GRAPHDEF.fields_by_name['versions'].message_type = versions__pb2._VERSIONDEF
_GRAPHDEF.fields_by_name['library'].message_type = function__pb2._FUNCTIONDEFLIBRARY
DESCRIPTOR.message_types_by_name['GraphDef'] = _GRAPHDEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphDef = _reflection.GeneratedProtocolMessageType('GraphDef', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHDEF,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:domi.tensorflow.GraphDef)
  })
_sym_db.RegisterMessage(GraphDef)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
